name: PowerShell Script Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-powershell-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run PowerShell script tests
      run: |
        pwsh -File ./scripts/test-script.ps1 > test-results.txt

    - name: Commit test results to gh-pages
      if: failure()
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout -b gh-pages
        mv test-results.txt index.html
        git add index.html
        git commit -m 'Update test results'
        git push --force origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}