name: PowerShell Script Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-powershell-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Run PowerShell script tests
      run: |
        pwsh -File ./scripts/test-script.ps1